version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-hamburgueria
    environment:
      - POSTGRESQL_DATABASE=hamburgueria
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
volumes:
  postgres_data:
